-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID NOT IN (
    SELECT TA.ITEM_ID
    FROM ITEM_TREE TA, ITEM_TREE TB
    WHERE TA.ITEM_ID = TB.PARENT_ITEM_ID
    GROUP BY TA.ITEM_ID
)
ORDER BY I.ITEM_ID DESC