-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_FISH ON A.FISH_TYPE = MAX_FISH.FISH_TYPE AND A.LENGTH = MAX_FISH.MAX_LENGTH
ORDER BY A.ID